#pragma once

const int CORAL_LAUNCHER_FLYWHEEL_RIGHT_CAN_ID = 30;
const int CORAL_LAUNCHER_FLYWHEEL_LEFT_CAN_ID = 31;
const int CORAL_LAUNCHER_INDEXER_RIGHT_CAN_ID = 32;
const int CORAL_LAUNCHER_INDEXER_LEFT_CAN_ID = 33;
const int CORAL_LAUNCHER_BEAM_BREAK_CAN_ID = 34;

const int ALGAE_REMOVER_ARM_CAN_ID = 40;
const int ALGAE_REMOVER_PUSH_CAN_ID = 41;

const int CLIMBER_WINCH_CAN_ID = 50;
